/*
 * This source file was generated by the Gradle 'init' task
 */
package controlunitsubsystem;

import controlunitsubsystem.impl.ControlUnitImpl;
import controlunitsubsystem.api.ControlUnit;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        ControlUnit controlUnit = new ControlUnitImpl("http://127.0.0.1:5000/send");
        controlUnit.dashboardTick();
    }
}
